# Generated by Django 5.1.1 on 2024-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='password',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='service_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
