# Generated by Django 5.1.1 on 2024-09-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
