# Generated by Django 5.1.1 on 2024-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_remove_user_role_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
